title: <p align="center"> Seshu Kumar Bangaru </p>
logo: "/assets/img/DSC_0924 copy.jpg"
description: A Solution Architect with Java/Python fullstack. 10+ Years of experience in E/CTRM Domain. A Budding Data Scientist
remote_theme: pages-themes/minimal@v0.2.0
theme: jekyll-theme-minimal
